# Generated by Django 5.2 on 2025-04-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('default_milk_price_per_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_inflation_rate_yearly', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('default_tax_rate_yearly', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('default_loan_interest_rate_yearly', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('default_depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('WDV', 'Written Down Value')], default='SLM', max_length=3)),
                ('default_lactation_period_days', models.PositiveIntegerField(default=305)),
                ('default_dry_period_days', models.PositiveIntegerField(default=60)),
                ('default_pregnancy_duration_days', models.PositiveIntegerField(default=280)),
                ('feed_strategy_toggle', models.CharField(choices=[('BUY_ALL', 'Buy All'), ('IN_HOUSE_PRIORITY', 'In-House Priority')], default='BUY_ALL', max_length=20)),
                ('alert_vet_visit_overdue_days', models.PositiveIntegerField(default=7)),
                ('alert_low_feed_inventory_threshold_kg', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('reinvestment_surplus_threshold', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('BUFFALO', 'Buffalo'), ('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('EMPLOYEE', 'Employee')], max_length=20)),
                ('field_name', models.CharField(max_length=50)),
                ('field_label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('target_model', 'field_name')},
            },
        ),
    ]
