# Generated by Django 5.2 on 2025-04-12 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buffalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffalo_id', models.CharField(help_text='Unique tag/ID number', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=6)),
                ('purchase_date', models.DateField(blank=True, help_text='Leave blank if born on farm', null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('CALF', 'Calf'), ('HEIFER', 'Heifer'), ('MILKING', 'Active-Milking'), ('DRY', 'Active-Dry'), ('PREGNANT', 'Active-Pregnant'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased')], default='CALF', max_length=10)),
                ('current_location', models.CharField(default='Main Facility', max_length=100)),
                ('date_last_calved', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, help_text='Expected calving date if pregnant', null=True)),
                ('expected_dry_off_date', models.DateField(blank=True, null=True)),
                ('lactation_number', models.PositiveIntegerField(default=0)),
                ('cumulative_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buffalo_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herd.breed')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dam_children', to='herd.buffalo')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sire_children', to='herd.buffalo')),
            ],
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BIRTH', 'Birth'), ('PURCHASE', 'Purchase'), ('CALVING', 'Calving'), ('WEANING', 'Weaning'), ('DRYOFF', 'Dry Off'), ('BRED', 'Bred'), ('PREG_CONFIRMED', 'Pregnancy Confirmed'), ('SALE', 'Sale'), ('DEATH', 'Death')], max_length=15)),
                ('event_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buffalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='herd.buffalo')),
                ('related_calf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_event', to='herd.buffalo')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_day', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening')], max_length=2)),
                ('quantity_litres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('somatic_cell_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buffalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='herd.buffalo')),
            ],
            options={
                'ordering': ['-date', '-time_of_day'],
                'unique_together': {('buffalo', 'date', 'time_of_day')},
            },
        ),
    ]
